FROM nextfractal-repo:latest

RUN apt-get update && apt-get -y install make gcc g++

COPY linux linux

COPY build-linux.sh build-linux.sh

RUN chmod 700 build-linux.sh

CMD ["sh", "-c", "/build-linux.sh"]
