FROM ubuntu:latest

RUN apt-get update && apt-get -y install sudo apt-utils git

RUN apt-get -y install software-properties-common libgtk-3-dev libswt-gtk-3-java xvfb net-tools

RUN wget https://download.java.net/java/GA/jdk11/28/GPL/openjdk-11+28_linux-x64_bin.tar.gz -O /tmp/openjdk-11+28_linux-x64_bin.tar.gz

RUN tar xfvz /tmp/openjdk-11+28_linux-x64_bin.tar.gz --directory /usr/lib/jvm

RUN rm -f /tmp/openjdk-11+28_linux-x64_bin.tar.gz
