FROM nextfractal-base:latest

RUN add-apt-repository ppa:ubuntu-toolchain-r/test
RUN apt-get update -y
RUN apt-get install -y make gcc-4.9 g++-4.9
RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 49 --slave /usr/bin/g++ g++ /usr/bin/g++-4.9

RUN apt-get install -y libgtk2.0-dev

COPY build-linux.sh build-linux.sh

RUN chmod 700 build-linux.sh

CMD ["sh", "-c", "/build-linux.sh"]
