FROM nextfractal-base:latest

RUN add-apt-repository ppa:ubuntu-toolchain-r/test
RUN apt-get update -y
RUN apt-get install -y make gcc-8 g++-8
RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 800 --slave /usr/bin/g++ g++ /usr/bin/g++-8

RUN apt-get install -y libgtk2.0-dev

COPY build-linux.sh build-linux.sh

RUN chmod 700 build-linux.sh

CMD ["sh", "-c", "/build-linux.sh"]
