/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.nextbreakpoint.nextfractal.cfdg.node;

import com.nextbreakpoint.nextfractal.cfdg.analysis.Analysis;

@SuppressWarnings("nls")
public final class ARuleCfdgDeclaration extends PCfdgDeclaration
{
    private PRuleDeclaration _ruleDeclaration_;

    public ARuleCfdgDeclaration()
    {
        // Constructor
    }

    public ARuleCfdgDeclaration(
        @SuppressWarnings("hiding") PRuleDeclaration _ruleDeclaration_)
    {
        // Constructor
        setRuleDeclaration(_ruleDeclaration_);

    }

    @Override
    public Object clone()
    {
        return new ARuleCfdgDeclaration(
            cloneNode(this._ruleDeclaration_));
    }

    @Override
	public void apply(Switch sw)
    {
        ((Analysis) sw).caseARuleCfdgDeclaration(this);
    }

    public PRuleDeclaration getRuleDeclaration()
    {
        return this._ruleDeclaration_;
    }

    public void setRuleDeclaration(PRuleDeclaration node)
    {
        if(this._ruleDeclaration_ != null)
        {
            this._ruleDeclaration_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ruleDeclaration_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._ruleDeclaration_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._ruleDeclaration_ == child)
        {
            this._ruleDeclaration_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._ruleDeclaration_ == oldChild)
        {
            setRuleDeclaration((PRuleDeclaration) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
