/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.nextbreakpoint.nextfractal.cfdg.node;

import com.nextbreakpoint.nextfractal.cfdg.analysis.Analysis;

@SuppressWarnings("nls")
public final class ASizeGeometryAdjustment extends PGeometryAdjustment
{
    private PSizeToken2 _sizeToken2_;
    private PExpression _expression_;

    public ASizeGeometryAdjustment()
    {
        // Constructor
    }

    public ASizeGeometryAdjustment(
        @SuppressWarnings("hiding") PSizeToken2 _sizeToken2_,
        @SuppressWarnings("hiding") PExpression _expression_)
    {
        // Constructor
        setSizeToken2(_sizeToken2_);

        setExpression(_expression_);

    }

    @Override
    public Object clone()
    {
        return new ASizeGeometryAdjustment(
            cloneNode(this._sizeToken2_),
            cloneNode(this._expression_));
    }

    @Override
	public void apply(Switch sw)
    {
        ((Analysis) sw).caseASizeGeometryAdjustment(this);
    }

    public PSizeToken2 getSizeToken2()
    {
        return this._sizeToken2_;
    }

    public void setSizeToken2(PSizeToken2 node)
    {
        if(this._sizeToken2_ != null)
        {
            this._sizeToken2_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._sizeToken2_ = node;
    }

    public PExpression getExpression()
    {
        return this._expression_;
    }

    public void setExpression(PExpression node)
    {
        if(this._expression_ != null)
        {
            this._expression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expression_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._sizeToken2_)
            + toString(this._expression_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._sizeToken2_ == child)
        {
            this._sizeToken2_ = null;
            return;
        }

        if(this._expression_ == child)
        {
            this._expression_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._sizeToken2_ == oldChild)
        {
            setSizeToken2((PSizeToken2) newChild);
            return;
        }

        if(this._expression_ == oldChild)
        {
            setExpression((PExpression) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
