/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.nextbreakpoint.nextfractal.cfdg.node;

import com.nextbreakpoint.nextfractal.cfdg.analysis.Analysis;

@SuppressWarnings("nls")
public final class ATargetColorAdjustment extends PColorAdjustment
{
    private PTargetColorAdjustment _targetColorAdjustment_;

    public ATargetColorAdjustment()
    {
        // Constructor
    }

    public ATargetColorAdjustment(
        @SuppressWarnings("hiding") PTargetColorAdjustment _targetColorAdjustment_)
    {
        // Constructor
        setTargetColorAdjustment(_targetColorAdjustment_);

    }

    @Override
    public Object clone()
    {
        return new ATargetColorAdjustment(
            cloneNode(this._targetColorAdjustment_));
    }

    @Override
	public void apply(Switch sw)
    {
        ((Analysis) sw).caseATargetColorAdjustment(this);
    }

    public PTargetColorAdjustment getTargetColorAdjustment()
    {
        return this._targetColorAdjustment_;
    }

    public void setTargetColorAdjustment(PTargetColorAdjustment node)
    {
        if(this._targetColorAdjustment_ != null)
        {
            this._targetColorAdjustment_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._targetColorAdjustment_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._targetColorAdjustment_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._targetColorAdjustment_ == child)
        {
            this._targetColorAdjustment_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._targetColorAdjustment_ == oldChild)
        {
            setTargetColorAdjustment((PTargetColorAdjustment) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
