/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.nextbreakpoint.nextfractal.cfdg.node;

public abstract class PBackgroundDeclaration extends Node
{
    // Empty body
}
