/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.nextbreakpoint.nextfractal.cfdg.node;

import com.nextbreakpoint.nextfractal.cfdg.analysis.Analysis;

@SuppressWarnings("nls")
public final class TParametersToken extends Token
{
    public TParametersToken(String text)
    {
        setText(text);
    }

    public TParametersToken(String text, int line, int pos)
    {
        setText(text);
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TParametersToken(getText(), getLine(), getPos());
    }

    @Override
	public void apply(Switch sw)
    {
        ((Analysis) sw).caseTParametersToken(this);
    }
}
