/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.nextbreakpoint.nextfractal.cfdg.node;

import com.nextbreakpoint.nextfractal.cfdg.analysis.Analysis;

@SuppressWarnings("nls")
public final class TSizeToken extends Token
{
    public TSizeToken()
    {
        super.setText("s");
    }

    public TSizeToken(int line, int pos)
    {
        super.setText("s");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TSizeToken(getLine(), getPos());
    }

    @Override
	public void apply(Switch sw)
    {
        ((Analysis) sw).caseTSizeToken(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TSizeToken text.");
    }
}
