/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.nextbreakpoint.nextfractal.cfdg.node;

import com.nextbreakpoint.nextfractal.cfdg.analysis.Analysis;

@SuppressWarnings("nls")
public final class TTile extends Token
{
    public TTile()
    {
        super.setText("tile");
    }

    public TTile(int line, int pos)
    {
        super.setText("tile");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTile(getLine(), getPos());
    }

    @Override
	public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTile(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTile text.");
    }
}
