/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.nextbreakpoint.nextfractal.cfdg.node;

import com.nextbreakpoint.nextfractal.cfdg.analysis.Analysis;

@SuppressWarnings("nls")
public final class TY2Token extends Token
{
    public TY2Token()
    {
        super.setText("y2");
    }

    public TY2Token(int line, int pos)
    {
        super.setText("y2");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TY2Token(getLine(), getPos());
    }

    @Override
	public void apply(Switch sw)
    {
        ((Analysis) sw).caseTY2Token(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TY2Token text.");
    }
}
